# Generated by Django 5.2.12 on 2026-04-01 00:00

import django.db.models.deletion
from django.db import migrations, models


def seed_default_teacher_profile(apps, schema_editor):
    CustomUser = apps.get_model("home_auth", "CustomUser")
    Department = apps.get_model("faculty", "Department")
    TeacherProfile = apps.get_model("faculty", "TeacherProfile")

    department, _ = Department.objects.get_or_create(
        name="General Studies",
        defaults={"description": "Default academic department created for the teacher module."},
    )

    teacher_user = CustomUser.objects.filter(email="teachers@gmail.com").first()
    if teacher_user is None:
        return

    TeacherProfile.objects.update_or_create(
        email="teachers@gmail.com",
        defaults={
            "user": teacher_user,
            "department": department,
            "employee_id": "TCH-001",
            "first_name": teacher_user.first_name or "Teacher",
            "last_name": teacher_user.last_name or "User",
            "phone_number": "0000000000",
            "qualification": "Teacher Account",
            "hire_date": "2026-04-01",
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home_auth", "0003_alter_passwordresetrequest_options_and_more"),
        ("student", "0002_alter_student_options_alter_student_admission_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ["start_date", "title"]},
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("qualification", models.CharField(max_length=255)),
                ("hire_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="faculty.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_profile",
                        to="home_auth.customuser",
                    ),
                ),
            ],
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("credit_hours", models.PositiveSmallIntegerField(default=3)),
                ("description", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="faculty.department",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subjects",
                        to="faculty.teacherprofile",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_of_week", models.CharField(choices=[("Monday", "Monday"), ("Tuesday", "Tuesday"), ("Wednesday", "Wednesday"), ("Thursday", "Thursday"), ("Friday", "Friday"), ("Saturday", "Saturday")], max_length=10)),
                ("target_class", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=10)),
                ("room", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="faculty.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="faculty.teacherprofile",
                    ),
                ),
            ],
            options={"ordering": ["day_of_week", "start_time"]},
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("target_class", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=10)),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("total_marks", models.PositiveIntegerField(default=100)),
                ("description", models.TextField(blank=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="faculty.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="faculty.teacherprofile",
                    ),
                ),
            ],
            options={"ordering": ["exam_date", "start_time"]},
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=5)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="faculty.exam",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_results",
                        to="faculty.teacherprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="student.student",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(fields=("department", "name"), name="faculty_subject_department_id_name_baa88039_uniq"),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(fields=("day_of_week", "target_class", "section", "start_time"), name="faculty_timetableentry_day_of_week_target_class_section_start_time_08f15d48_uniq"),
        ),
        migrations.AddConstraint(
            model_name="examresult",
            constraint=models.UniqueConstraint(fields=("exam", "student"), name="faculty_examresult_exam_id_student_id_f56d79ff_uniq"),
        ),
        migrations.RunPython(seed_default_teacher_profile, migrations.RunPython.noop),
    ]
