# Generated by Django 5.2.12 on 2026-04-01 00:00

from django.db import migrations, models


def seed_demo_student(apps, schema_editor):
    Parent = apps.get_model("student", "Parent")
    Student = apps.get_model("student", "Student")

    if Student.objects.filter(student_id="STU-001").exists():
        return

    parent = Parent.objects.create(
        father_name="Student Father",
        father_occupation="Engineer",
        father_mobile="0600000001",
        father_email="father.student@gmail.com",
        mother_name="Student Mother",
        mother_occupation="Teacher",
        mother_mobile="0600000002",
        mother_email="mother.student@gmail.com",
        present_address="Casablanca",
        permanent_address="Casablanca",
    )
    Student.objects.create(
        first_name="Student",
        last_name="User",
        student_id="STU-001",
        gender="Male",
        date_of_birth="2010-01-15",
        student_class="Grade 7",
        joining_date="2024-09-01",
        mobile_number="0600000003",
        admission_number="ADM-001",
        section="A",
        parent=parent,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_image",
            field=models.FileField(blank=True, null=True, upload_to="students/"),
        ),
        migrations.RunPython(seed_demo_student, migrations.RunPython.noop),
    ]
