# Generated by Django 5.2.12 on 2026-04-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_options_alter_student_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['father_name', 'mother_name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.parent'),
        ),
    ]
