# Generated by Django 5.2.12 on 2026-04-01 00:00

from django.contrib.auth.hashers import make_password
from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_reset_token():
    return get_random_string(32)


def seed_demo_users(apps, schema_editor):
    CustomUser = apps.get_model("home_auth", "CustomUser")

    demo_users = [
        {
            "email": "student@gmail.com",
            "password": "student",
            "first_name": "Student",
            "last_name": "User",
            "is_student": True,
            "is_teacher": False,
            "is_admin": False,
            "is_staff": False,
            "is_superuser": False,
        },
        {
            "email": "admin@gmail.com",
            "password": "admin",
            "first_name": "Admin",
            "last_name": "User",
            "is_student": False,
            "is_teacher": False,
            "is_admin": True,
            "is_staff": True,
            "is_superuser": True,
        },
        {
            "email": "teachers@gmail.com",
            "password": "teacher",
            "first_name": "Teacher",
            "last_name": "User",
            "is_student": False,
            "is_teacher": True,
            "is_admin": False,
            "is_staff": False,
            "is_superuser": False,
        },
    ]

    for payload in demo_users:
        password = payload.pop("password")
        user, _ = CustomUser.objects.get_or_create(
            email=payload["email"],
            defaults={**payload, "username": payload["email"], "is_authorized": True},
        )
        for key, value in payload.items():
            setattr(user, key, value)
        user.username = payload["email"]
        user.is_authorized = True
        user.login_token = None
        user.password = make_password(password)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0002_customuser_is_authorized_customuser_login_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(default=generate_reset_token, editable=False, max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="password_reset_requests",
                        to="home_auth.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password reset request",
                "verbose_name_plural": "Password reset requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(seed_demo_users, migrations.RunPython.noop),
    ]
