# Generated by Django 5.2.12 on 2026-04-01 15:25

import home_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', home_auth.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default=home_auth.models.generate_reset_token, editable=False, max_length=32, unique=True),
        ),
    ]
